"""add_spaces_and_parent_image

Revision ID: b3c4d5e6f7g8
Revises: a2b3c4d5e6f7
Create Date: 2026-05-07

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3c4d5e6f7g8'
down_revision: Union[str, None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spaces',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('image_assets', sa.Column('space_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('image_assets', sa.Column('parent_image_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_image_assets_space_id', 'image_assets', 'spaces', ['space_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_image_assets_parent_image_id', 'image_assets', 'image_assets', ['parent_image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_image_assets_parent_image_id', 'image_assets', type_='foreignkey')
    op.drop_constraint('fk_image_assets_space_id', 'image_assets', type_='foreignkey')
    op.drop_column('image_assets', 'parent_image_id')
    op.drop_column('image_assets', 'space_id')
    op.drop_table('spaces')
    # ### end Alembic commands ###
